//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pandemic.Prism.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pandemic.Prism.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add details.
        /// </summary>
        public static string AddDetails {
            get {
                return ResourceManager.GetString("AddDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add document image.
        /// </summary>
        public static string AddImage {
            get {
                return ResourceManager.GetString("AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add report.
        /// </summary>
        public static string AddReport {
            get {
                return ResourceManager.GetString("AddReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an address..
        /// </summary>
        public static string AddressError {
            get {
                return ResourceManager.GetString("AddressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your address....
        /// </summary>
        public static string AddressPlaceHolder {
            get {
                return ResourceManager.GetString("AddressPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin reports.
        /// </summary>
        public static string AdminReports {
            get {
                return ResourceManager.GetString("AdminReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangeTitle {
            get {
                return ResourceManager.GetString("ChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check history.
        /// </summary>
        public static string CheckHistory {
            get {
                return ResourceManager.GetString("CheckHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a new password confirmation.
        /// </summary>
        public static string ConfirmNewPasswordError {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and the confirmation does not match.
        /// </summary>
        public static string ConfirmNewPasswordError2 {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the confirmation for new password.
        /// </summary>
        public static string ConfirmNewPasswordPlaceHolder {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate internet connection.
        /// </summary>
        public static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create report.
        /// </summary>
        public static string CreateReport {
            get {
                return ResourceManager.GetString("CreateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your password.
        /// </summary>
        public static string CurrentPasswordError {
            get {
                return ResourceManager.GetString("CurrentPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your current password.
        /// </summary>
        public static string CurrentPasswordPlaceHolder {
            get {
                return ResourceManager.GetString("CurrentPasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a document.
        /// </summary>
        public static string DocumentError {
            get {
                return ResourceManager.GetString("DocumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your document number....
        /// </summary>
        public static string DocumentPlaceHolder {
            get {
                return ResourceManager.GetString("DocumentPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the document of the reported.
        /// </summary>
        public static string DocumentPlaceHolderRep {
            get {
                return ResourceManager.GetString("DocumentPlaceHolderRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an email.
        /// </summary>
        public static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to example@domain.com.
        /// </summary>
        public static string EmailExamp {
            get {
                return ResourceManager.GetString("EmailExamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email....
        /// </summary>
        public static string EmailPlaceHolder {
            get {
                return ResourceManager.GetString("EmailPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency.
        /// </summary>
        public static string Emergency {
            get {
                return ResourceManager.GetString("Emergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user have a big problem, call support.
        /// </summary>
        public static string Error3 {
            get {
                return ResourceManager.GetString("Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a first name.
        /// </summary>
        public static string FirstNameError {
            get {
                return ResourceManager.GetString("FirstNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your first name....
        /// </summary>
        public static string FirstNamePlaceHolder {
            get {
                return ResourceManager.GetString("FirstNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the first name of the reported.
        /// </summary>
        public static string FirstNamePlaceHolderRep {
            get {
                return ResourceManager.GetString("FirstNamePlaceHolderRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From camera.
        /// </summary>
        public static string FromCamera {
            get {
                return ResourceManager.GetString("FromCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From gallery.
        /// </summary>
        public static string FromGallery {
            get {
                return ResourceManager.GetString("FromGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you must add document image.
        /// </summary>
        public static string ImageError {
            get {
                return ResourceManager.GetString("ImageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a last name.
        /// </summary>
        public static string LastNameError {
            get {
                return ResourceManager.GetString("LastNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your last name.
        /// </summary>
        public static string LastNamePlaceHolder {
            get {
                return ResourceManager.GetString("LastNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the last name of the reported.
        /// </summary>
        public static string LastNamePlaceHolderRep {
            get {
                return ResourceManager.GetString("LastNamePlaceHolderRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify User.
        /// </summary>
        public static string ModifyTitle {
            get {
                return ResourceManager.GetString("ModifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a new password.
        /// </summary>
        public static string NewPasswordError {
            get {
                return ResourceManager.GetString("NewPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new password.
        /// </summary>
        public static string NewPasswordPlaceHolder {
            get {
                return ResourceManager.GetString("NewPasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirm.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password confirm.
        /// </summary>
        public static string PasswordConfirmError1 {
            get {
                return ResourceManager.GetString("PasswordConfirmError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirm does not match.
        /// </summary>
        public static string PasswordConfirmError2 {
            get {
                return ResourceManager.GetString("PasswordConfirmError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password confirm....
        /// </summary>
        public static string PasswordConfirmPlaceHolder {
            get {
                return ResourceManager.GetString("PasswordConfirmPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password.
        /// </summary>
        public static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User or password incorrect.
        /// </summary>
        public static string PasswordError2 {
            get {
                return ResourceManager.GetString("PasswordError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User or password incorrect.
        /// </summary>
        public static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password....
        /// </summary>
        public static string PasswordPlaceHolder {
            get {
                return ResourceManager.GetString("PasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password recover.
        /// </summary>
        public static string PasswordRecover {
            get {
                return ResourceManager.GetString("PasswordRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number....
        /// </summary>
        public static string PhoneError {
            get {
                return ResourceManager.GetString("PhoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a phone..
        /// </summary>
        public static string PhonePlaceHolder {
            get {
                return ResourceManager.GetString("PhonePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where do you want to take the picture.
        /// </summary>
        public static string PictureSource {
            get {
                return ResourceManager.GetString("PictureSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as.
        /// </summary>
        public static string RegisterAs {
            get {
                return ResourceManager.GetString("RegisterAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a role..
        /// </summary>
        public static string RegisterAsError {
            get {
                return ResourceManager.GetString("RegisterAsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a role....
        /// </summary>
        public static string RegisterAsPlaceHolder {
            get {
                return ResourceManager.GetString("RegisterAsPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rememberme in this device.
        /// </summary>
        public static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remembering....
        /// </summary>
        public static string Remembering {
            get {
                return ResourceManager.GetString("Remembering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User or password incorrect.
        /// </summary>
        public static string UserIncorrect {
            get {
                return ResourceManager.GetString("UserIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user has problems contact support.
        /// </summary>
        public static string UserProblem {
            get {
                return ResourceManager.GetString("UserProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated successfully.
        /// </summary>
        public static string UserUpdated {
            get {
                return ResourceManager.GetString("UserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid email.
        /// </summary>
        public static string ValidEmail {
            get {
                return ResourceManager.GetString("ValidEmail", resourceCulture);
            }
        }
    }
}
